### ISSUE TITLE
Server lagging a lot, 12 tps, restart fixed

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#101]
Take a look here:

https://timings.aikar.co/?id=ceff31410c374436a981e8bfb9f9b896

I am still running an old PS version because I am waiting for the new player heads feature to be fixed.

Is the lagg caused by PS or something else? It happens when a lot of players are online usually during evening. I have to restart to fix

**Comment by espidev** [comment]
The lag from PS seems to be from the old /ps view

Btw, the heads issue was from the fact that the heads you found were not actually real players, but were textures. The MHF heads should work

**Comment by espidev** [comment]
I don't think the consistent lag though is from PS at all though, it seems like it's just overall 1.14 being pretty slow...

**Comment by Leonardo-Fiori** [comment]
Ugh.. I don't know if mhf heads are enough, I need 4 of them I would love to use heat replicas of the original Minecraft ores. But I find only heads that are not owned by players..

Btw, may I ask you quickly what do you think is lagging the server down to hell then? I really suck at timings 😅 and that happens rarely.. it's not constant all over the day

**Comment by espidev** [comment]
I did spend last week trying to add support for the custom heads (base64). It will technically be in 2.6.0, but /ps hide and /ps unhide will not work properly because I have to use Minecraft's /data command which doesn't support multiple worlds. Unfortunately, Spigot doesn't support custom heads at all, so for now it's basically a hack.

Looking at your timings, it looks to just be general lag (entities, chunk loading, etc.)
This has been an issue for me too on 1.14, since performance has just been much worse on this version :/

Hopefully 1.15 fixes things? I mean you could ask around about your timings, but I suspect it's just general 1.14 slowness
