### ISSUE TITLE
Flags Bug

### ISSUE THREAD

**Issue by Synthhero** [espidev/ProtectionStones#92]
Config edits dont apply to already placed stones.
Why every time I have to change a flag at the block-config in order to be applied I have to break and replace the protection stone?
For example when I set pvp allow from pvp deny, It doesnt let me pvp inside the region after /ps reload or server restart. The changes get applied if only i break and replace the same stone.

**Comment by espidev** [comment]
That's not a bug, it's to preserve user flag settings.

If you wanted to update all regions' flags, use /ps admin flag

**Comment by Synthhero** [comment]
It is a bug. What If I have 400 players and I want to change something at the config of the diamond ore protection block? Do I have to break all of their blocks and replace them one by one?

**Comment by Synthhero** [comment]
What if the change has to be applied at non-flag oriented stuff at the config file?

**Comment by espidev** [comment]
If you wanted to change other settings, you can use /ps admin recreate which recreates protection regions based on config settings (except for the flags)

**Comment by Synthhero** [comment]
Why doesnt /ps reload doesn't do what it's meant to do. Realoading all of the config files? It's simpler.

**Comment by espidev** [comment]
/ps reload only the config files into memory, it does not change any stored data. Server owners choose when and if they want to update and change actual stored data, because doing it at every reload will be very laggy, risky, and also might not even be desired by some admins.

A /ps reload doing region checks would have to loop through EVERY region in order to do the update, even if the changes were not region related. I decided back then to let admins update when they want to or need to separately.

I do know there is a lack of an option for /ps flag admin to apply to specific region types, but that will be worked on (you could file issue for it if interested)
